Error generating report: 'CrimeAnalyzer' object has no attribute 'load_data'
Traceback (most recent call last):
  File "analyze_crime_data.py", line 148, in main
    analyzer.load_data()
AttributeError: 'CrimeAnalyzer' object has no attribute 'load_data'


Analysis generated at: Sun Dec  8 08:36:43 UTC 2024
